Punctuations edits from issue #799
AICC/CMI-5_Spec_Current pull request #800
Opened 2023-07-21 14:34 UTC by MartinKoob

Adding missing periods to sentences in **Description** and **Value Space** fields as well as converting one list of values from a blockquote to a list for consistency.

2023-07-21 14:43 UTC, MrBillMcDonald commented
Per sub-group meeting ready to submit to monthly meeting.

2023-08-04 15:10 UTC, brianjmiller requested changes

2023-08-04 15:10 UTC, brianjmiller commented on cmi5_spec.md
> +      <p><strong>Value space:</strong>"Passed", "Completed", "CompletedAndPassed", CompletedOrPassed, "NotApplicable"</p>
```suggestion
      <p><strong>Value space:</strong>"Passed", "Completed", "CompletedAndPassed", "CompletedOrPassed", "NotApplicable"</p>
```

2023-08-04 15:12 UTC, brianjmiller approved these changes

2023-08-04 15:15 UTC, brianjmiller commented on cmi5_spec.md
> +      <p><strong>Value space:</strong>"Passed", "Completed", "CompletedAndPassed", "CompletedOrPassed", "NotApplicable"</p>
```suggestion
      <p><strong>Value space: </strong>"Passed", "Completed", "CompletedAndPassed", "CompletedOrPassed", "NotApplicable"</p>
```

2023-08-04 15:19 UTC, MrBillMcDonald commented
Approved per Aug-4-2023 Meeting

2023-08-04 15:19 UTC, merged